export const GET_ALL_PUBLICATION = 'GET_ALL_PUBLICATION';
export const UPDATED_USER_PUB = 'UPDATED_USER_PUB';
export const LOADING_PUBLICATIONS = 'LOADING_PUBLICATIONS';
export const ERROR_TO_GET_ALL_PUBLICATION = 'ERROR_TO_GET_ALL_PUBLICATION';