export const GET_ALL_PUBLICATION = 'GET_ALL_PUBLICATION';
export const GET_PUBLICATION_BY_USER = 'GET_PUBLICATION_BY_USER';
export const LOADING_PUBLICATIONS = 'LOADING_PUBLICATIONS';
export const ERROR_TO_GET_ALL_PUBLICATION = 'ERROR_TO_GET_ALL_PUBLICATION';